modLoader="javafml"
loaderVersion="[25,)"
issueTrackerURL="https://github.com/kosma/mariadb-jdbc-mod/issues"
license="GPLv2 with FOSS Exception"

[[mods]]
modId="mariadb_jdbc"
version="${version}"
displayName="MariaDB JDBC"
displayURL="https://www.curseforge.com/minecraft/mc-mods/mariadb-jdbc"
logoFile="icon.png"
authors="MariaDB Corporation Ab., Kosmolot"
description='''MariaDB JDBC Driver for Fabric and Forge'''
